[package]
name = "tree-nvim-rs"
version = "0.1.0"
authors = ["LI Tao <litao912002@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# nvim-rs = "0.1.0"
# TODO: use the version in crate.io. Currently only the master version has the working socket connection
nvim-rs = { path = "/data00/litao.91/repos/nvim-rs", features=["use_async-std"] }
# tokio = { version = "0.2.9", features = ["sync", "rt-core", "macros", "io-util", "tcp", "uds", "process", "io-std", "dns", "rt-threaded", "io-driver", "fs"] }
async-trait = "0.1.18"
simplelog = "0.7.4"
log = "0.3.7"
fork = "0.1.10"
async-std = "1.4.0"
backtrace = "0.3.42"
unicode-width = "0.1.7"
futures = { version = "0.3.1", features = ["io-compat"] }
